### ISSUE TITLE
the version of opencv

### ISSUE THREAD

**Issue by ytwas** [hritam-98/ICT-MedSeg#8]
When I tried to run 'python main.py' , an error occured:
> python main.py                                                                                                                                                       
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from dataloaders.dataset import (BaseDataSets, RandomGenerator,
  File "/home/ytw/win10-share/gitcode/ICT-MedSeg/dataloaders/dataset.py", line 2, in <module>
    import cv2
  File "/home/ytw/anaconda3/envs/torch/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

I have googled but found nothing. Does it have something to do with the version of opencv?

**Comment by ytwas** [comment]
the version of opencv and python must be compatible
